# Generated by Django 4.2.5 on 2023-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество(при наличии)')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('salary', models.IntegerField(verbose_name='Сумма договора, ₽')),
            ],
        ),
    ]
