# Generated by Django 4.2.5 on 2023-09-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
