# Generated by Django 4.2.5 on 2023-09-23 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbcore', '0003_alter_applicationdata_user_inputdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputData',
            new_name='ImportData',
        ),
    ]
