# Generated by Django 4.2.5 on 2023-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0004_rename_inputdata_importdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл (импорт)'),
        ),
    ]
