# Generated by Django 4.2.5 on 2023-09-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0005_alter_importdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='predicted_files/', verbose_name='Обработанные данные')),
                ('import_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicteddatas', to='dbcore.importdata', verbose_name='Ссылка на полученный файл (импорт)')),
            ],
        ),
    ]
