# Generated by Django 4.2.5 on 2023-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0006_predictdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictdata',
            name='model_type',
            field=models.CharField(default='test', max_length=10, verbose_name='Вид модели (лайт или полная)'),
            preserve_default=False,
        ),
    ]
